// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTY9vxscMkijoehD2yB6Ah4z5rFWasOz4',
    appId: '1:732493093597:web:74692e8f4c0ff1d454d934',
    messagingSenderId: '732493093597',
    projectId: 'fir-flutter-codelab-5268e',
    authDomain: 'fir-flutter-codelab-5268e.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-5268e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY6RBdF0sYF7lU7JFFt3uxCPzJ_m_Bqtw',
    appId: '1:732493093597:android:9178679a8c3690b154d934',
    messagingSenderId: '732493093597',
    projectId: 'fir-flutter-codelab-5268e',
    storageBucket: 'fir-flutter-codelab-5268e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMpwXZ_qyZtV5xs-NGmtZytx8yoqDK_RY',
    appId: '1:732493093597:ios:f9941b81a62d69e954d934',
    messagingSenderId: '732493093597',
    projectId: 'fir-flutter-codelab-5268e',
    storageBucket: 'fir-flutter-codelab-5268e.appspot.com',
    iosClientId: '732493093597-u72blutbuo24n2vh6tlqnqv2s6g8iuia.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMpwXZ_qyZtV5xs-NGmtZytx8yoqDK_RY',
    appId: '1:732493093597:ios:f9941b81a62d69e954d934',
    messagingSenderId: '732493093597',
    projectId: 'fir-flutter-codelab-5268e',
    storageBucket: 'fir-flutter-codelab-5268e.appspot.com',
    iosClientId: '732493093597-u72blutbuo24n2vh6tlqnqv2s6g8iuia.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
